### ISSUE TITLE
Make NumberFormatter public

### ISSUE THREAD

**Issue by tobyzerner** [jrmajor/fluent-php#10]
The brilliant `NumberFormatter` implementation is marked as `@internal`.

I would like to use it as a helper in a custom Fluent function I'm implementing. Would it be possible to open it up? Perhaps it would even be worthy of extraction into its own repo/package, much like PluralRules?

**Comment by jrmajor** [comment]
Thank you, but I think its brilliance is debatable :). I tried to make [jrmajor/pluralrules](https://github.com/jrmajor/pluralrules) solid and suitable for being used by different packages, but this is not the case with `NumberFormatter`. It's created in the simplest possible way with implementing `NUMBER()` function in mind, and because of that it's a bit fragile and its API could use much improvement.

If it is useful in more cases, I will consider extracting this, with a scope limited to what it is now and refined API. For now, you can use `@internal` stuff, just lock `jrmajor/fluent` to exact version instead of using caret range and make sure to write tests for your code that uses `NumberFormatter`, because changes to internal APIs aren't mentioned in changelog.

**Comment by tobyzerner** [comment]
Sounds good, thank you!
